version: "3.9"

services:
  frontend:
    build:
      context: ../frontend
    expose:
      - "3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
    networks:
      - app-network

  backend:
    build:
      context: ../backend
    expose:
      - "5000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ../nginx/default.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

    depends_on:
      - frontend
      - backend

    networks:
      - app-network

networks:
  app-network:
    driver: bridge